# cargo-release configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Don't push to crates.io automatically (GitHub Actions will do it)
publish = false

# Always push tags after creating them
push = true

# Tag format: v0.1.0
tag-name = "v{{version}}"
tag-message = "Release {{version}}"

# Commit message for version bump
pre-release-commit-message = "Release {{version}}"

# Don't create a separate commit for dev version bump
no-dev-version = true

# Sign tags (optional - remove if you don't use GPG signing)
# sign-tag = true

# Pre-release checks
pre-release-replacements = [
  # Update version in README.md if you reference it
  # { file = "README.md", search = "version = \"[0-9.]+\"", replace = "version = \"{{version}}\"" },
]

# Which branches are allowed for releases
allow-branch = ["main"]

# Don't allow dirty working directory
#disable-push = false
#disable-tag = false
